### ISSUE TITLE
Create JSON File for Burnt Brotta Recipe Data

### ISSUE THREAD

**Issue by amri-tah** [amri-tah/burntbrotta#1]
**Description:**
We need to create a JSON file to store the recipe details for the "Burnt Brotta" recipe dynamically. This file will be used to render dynamic recipe pages and can include multiple recipes in the future. 

### Task:
- **Extract the following from each recipe page and create a JSON file to store recipe data**:
  - Each recipe will have the following fields:
    - `id`: Unique identifier for each recipe.
    - `name`: Name of the recipe.
    - `image`: URL or path to an image for the recipe.
    - `description`: Short description of the recipe.
    - `time`: Time required for the recipe (e.g., "2 hours").
    - `servings`: Number of servings the recipe makes.
    - `difficulty`: Difficulty level of the recipe (e.g., "Intermediate").
    - `ingredients`: List of ingredients required.
    - `instructions`: Step-by-step cooking instructions.
    - `reviews`: Average rating of the recipe (e.g., from 1 to 5 stars).
    - `tags`: Additional tags for categorization (e.g., time, servings, difficulty).

### Example JSON structure:

```json
[
  {
    "id": 1,
    "name": "Burnt Brotta",
    "image": "path/to/image.jpg",
    "description": "Delight in the Flaky Marvel of Homemade Parottas! Experience the Magic of Homemade Parottas: Flaky, Crispy, and Oh-So-Tasty!",
    "time": "2 hours",
    "servings": "1 serving",
    "difficulty": "Intermediate",
    "ingredients": [
      "2 cups Maida (All-Purpose Flour)",
      "¼ cup Milk at room temperature",
      "1 teaspoon Sugar",
      "Salt as needed",
      "Water as needed"
    ],
    "instructions": [
      "In a large plate or mixing bowl, add 2 cups maida, 1 teaspoon sugar, salt as needed. Roughly mix it together and make a well in the center.",
      "Pour ¼ cup milk (at room temperature) and add water as needed.",
      "Knead into a soft pliable dough. Add 1 tablespoon oil on top.",
      "Repeat special kneading technique until dough is soft and smooth.",
      "Add 2 tablespoons oil on top, cover with a damp kitchen towel, and rest for at least 2 hours."
      // Add remaining steps...
    ],
    "reviews": {
      "rating": 5,
      "comments": [
        "Great recipe! Very tasty.",
        "A little tricky to make, but worth it."
      ]
    },
    "tags": ["2 hours", "1 serving", "Intermediate"]
  }
]
```

### Steps:
1. Create the `recipes.json` file in the project's root directory.
2. Ensure the ingredients and instructions are structured as lists.

**Comment by Samhitha-07** [comment]
I would like to work on this issue. I have experience with JSON data handling and creating structured files for dynamic rendering. Please assign this issue to me so I can get started.

**Comment by SaranHiruthikM** [comment]
Heyy!! Since I've worked with JSON data before, I've a pretty good idea to fix the issue. I'd love to solve this if you assign this to me. @amri-tah

**Comment by amri-tah** [comment]
Hey, you've been assigned this issue under Amrita Winter of Code! Please ensure to raise a PR by `28/12/2024`, or it will be reassigned to someone else. Best of luck! 🫡

**Comment by SaranHiruthikM** [comment]
@amri-tah  have completed the issue with the PR #6
