### ISSUE TITLE
Popular Recipe section's (Home Page) images when click are showing page not found error

### ISSUE THREAD

**Issue by SaranHiruthikM** [amri-tah/burntbrotta#12]
In the website, in the popular recipes section, on clicking the dish's image it is showing error 404 (page not found).. as the url of the page is not modified according to new file format. (`recipe.html`, `script.js`). Can change the url like `?id=1` to solve the issue

**Comment by Harish1604** [comment]
Can you assign this to me @hirux06

**Comment by SaranHiruthikM** [comment]
Sorry @Harish1604!! I'm not a maintainer of this repo. Kindly ask @amri-tah to assign this to you. Thanks

**Comment by Harish1604** [comment]
OK. Can u assign this to me @amri-tah. Very eager to solve this issue..

**Comment by amri-tah** [comment]
Hey @Harish1604, you've been assigned this issue under Amrita Winter of Code! Please ensure to raise a PR by 31/12/2024, or it will be reassigned to someone else. Best of luck! 🫡

**Comment by Harish1604** [comment]
Solved in #14 @amri-tah
