### ISSUE TITLE
Form Validation for each recipe

### ISSUE THREAD

**Issue by akshayks13** [amri-tah/burntbrotta#15]
There isnt any form validation for the recipe page and also needs some UI Enhancements 

And I am interested in doing this 

So @amri-tah  can I take up this

**Comment by amri-tah** [comment]
Sure @akshayks13, your deadline for completing this issue is `31/12/2024`. There might be a delay in PR reviews till the end of this month though.

**Comment by amri-tah** [comment]
@akshayks13 Before you implement this, it would be great if you could let me know what changes you will be making exactly. (Something like a Figma prototype)

**Comment by akshayks13** [comment]
> @akshayks13 Before you implement this, it would be great if you could let me know what changes you will be making exactly. (Something like a Figma prototype)

**Styling Improvements**

1. Enhance padding for all form elements to ensure a cleaner and more polished design.
2. Add hover effects for input fields and buttons to improve user interaction and visual feedback.

**Validation with JavaScript**

1. Create a new JavaScript file dedicated to handling basic validations, such as:
 Email validation using regular expressions.
2. Ensuring all required fields (e.g., name, email, and message) are completed.
3. Highlight invalid fields dynamically with visual cues (e.g., red borders or error messages).

**Submission Feedback**

1. After validation, update the form content dynamically to display a confirmation message like "Form Submitted."
2. Alternatively, show an alert to notify the user of successful submission.

**Comment by amri-tah** [comment]
> > @akshayks13 Before you implement this, it would be great if you could let me know what changes you will be making exactly. (Something like a Figma prototype)
> 
> **Styling Improvements**
> 
> 1. Enhance padding for all form elements to ensure a cleaner and more polished design.
> 2. Add hover effects for input fields and buttons to improve user interaction and visual feedback.
> 
> **Validation with JavaScript**
> 
> 1. Create a new JavaScript file dedicated to handling basic validations, such as:
>    Email validation using regular expressions.
> 2. Ensuring all required fields (e.g., name, email, and message) are completed.
> 3. Highlight invalid fields dynamically with visual cues (e.g., red borders or error messages).
> 
> **Submission Feedback**
> 
> 1. After validation, update the form content dynamically to display a confirmation message like "Form Submitted."
> 2. Alternatively, show an alert to notify the user of successful submission.

LGTM @akshayks13! Please refer the recipe.json file for the format of the reviews for the input fields.

**Comment by akshayks13** [comment]
@amri-tah , can i get suggestions ?

After the form is submitted , should I add a normal alert message or can I replace the form content with a message

Like this
<img width="1427" alt="Screenshot 2024-12-25 at 5 03 48 PM" src="https://github.com/user-attachments/assets/9b919bbe-3e4f-4e2d-b787-620eb560e906" />

Which would you sujjest ?

**Comment by amri-tah** [comment]
> @amri-tah , can i get suggestions ?
> 
> After the form is submitted , should I add a normal alert message or can I replace the form content with a message
> 
> Like this <img alt="Screenshot 2024-12-25 at 5 03 48 PM" width="1427" src="https://private-user-images.githubusercontent.com/143313500/398568749-9b919bbe-3e4f-4e2d-b787-620eb560e906.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUxMjY4MDUsIm5iZiI6MTczNTEyNjUwNSwicGF0aCI6Ii8xNDMzMTM1MDAvMzk4NTY4NzQ5LTliOTE5YmJlLTNlNGYtNGUyZC1iNzg3LTYyMGViNTYwZTkwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIyNVQxMTM1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OWUwZjMxNzQ1M2FmMzM4ZDc0OTNmZWJhY2E4NjYxNjgxNTEzMDZjMWQ2YjQ1NDBmZTVmMzBjM2M1MDAwMzFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.8B7X13kNcQrqwkjMVVAgUg3A1p7QWRl4RNdj5uIvo4g">
> 
> Which would you sujjest ?

Hey, I think a toast message (styled to fit the style of the page) would do!
