### ISSUE TITLE
Make the Catalog Page Dynamic Using Recipe JSON

### ISSUE THREAD

**Issue by amri-tah** [amri-tah/burntbrotta#2]
**Description**:
Refactor the `catalog.html` page to dynamically render catalog from the recipe JSON file while maintaining the current design and styling.

### Tasks  
1. **Integrate with Catalog Page**  
   - Replace hardcoded content in `catalog.html` with dynamic content generated from the JSON file.  
   - Use JavaScript to dynamically create and populate catalog items based on JSON data.
2. **Styling Consistency**  
   - Preserve the existing styling defined in `catalog.css`.  
   - Test responsiveness and adjust CSS as needed to ensure the page displays correctly across devices.

#### Deliverables  
1. Updated `catalog.html` with placeholders for dynamic rendering.  
2. A JavaScript script to fetch, parse, and render recipe data dynamically.  
3. A fully functional and styled catalog page with dynamic content from the recipe JSON.

Ensure the code is modular, maintainable, and ready for future enhancements.

**Comment by Adhikkesh** [comment]
@amri-tah 
I am interested in working on this issue. I have experience with JavaScript and dynamic content rendering and can ensure the catalog maintains its current design and responsiveness

**Comment by SaranHiruthikM** [comment]
Since I've worked on issue like this before. I'd want you to assign me this issue. @amri-tah

**Comment by amri-tah** [comment]
Hey @hirux06 ! Under Amrita Winter of Code, only one issue can be assigned per person per repository. Please complete your currently assigned issue and raise a PR before requesting another. Looking forward to your contributions!

**Comment by Keerthivasan-Venkitajalam** [comment]
I'd like to take up this issue 😁... Assign this to me please @amri-tah

**Comment by Keerthivasan-Venkitajalam** [comment]
I'd like to take up this issue 😁... Please assign this if it's not already assigned to someone @amri-tah.

**Comment by amri-tah** [comment]
Hey @Keerthivasan-Venkitajalam, you've been assigned this issue under Amrita Winter of Code! Please ensure to raise a PR by `10/01/2025`, or it will be reassigned to someone else. Best of luck! 🫡

**Comment by IAmRiteshKoushik** [comment]
@amri-tah if this issue has been completed, please close it. The issue completion is yet to reflect on the profile of the contributor.
