### ISSUE TITLE
Make Recipe Pages Dynamic Using Recipe JSON

### ISSUE THREAD

**Issue by amri-tah** [amri-tah/burntbrotta#3]
**Description:**
Refactor individual recipe pages (`r1page.html`, `r2page.html`, etc.) to dynamically generate content based on recipe data from the pre-existing JSON file.  

### Tasks  
1. **Page Refactoring**  
   - Replace the static content in individual recipe pages (`r1page.html`, `r2page.html`, etc.) with `recipe.html` which has placeholders for dynamic content.
   - Use JavaScript to dynamically populate the page based on the recipe ID from the URL or query parameters.  

2. **Styling Consistency**  
   - Ensure the dynamic content adheres to the current page design.  

3. **Routing and Navigation**  
   - Implement a method to determine the recipe ID dynamically (e.g., query parameters like `?id=r1`).  
   - Ensure each recipe page is accessible via a unique URL based on its ID.  

### Deliverables  
1. Updated `recipe.html` file with placeholders for dynamic content.  
2. A reusable JavaScript function to fetch and render recipe data dynamically.  
3. Fully functional and styled individual recipe pages with content loaded from the recipe JSON.

**Comment by rev-sin** [comment]
I'm interested, count me in :+1:  @amri-tah

**Comment by SaranHiruthikM** [comment]
I've previously worked on the issues like this before. So, I'd love if you assign me this issue!! @amri-tah

**Comment by amri-tah** [comment]
Hey @hirux06 ! Under Amrita Winter of Code, only one issue can be assigned per person per repository. Please complete your currently assigned issue and raise a PR before requesting another. Looking forward to your contributions!

**Comment by SaranHiruthikM** [comment]
Since my previous issue has been closed, can I take up this issue now 😢 @amri-tah

**Comment by amri-tah** [comment]
Yepp, issue assigned to @hirux06 under Amrita Winter of Code. Please ensure to raise a PR by `4/01/2025`, or it will be reassigned to someone else.

**Comment by SaranHiruthikM** [comment]
Issue solved at #7
