### ISSUE TITLE
Enhancing the Footer design 

### ISSUE THREAD

**Issue by akshayks13** [amri-tah/burntbrotta#8]
The copyright section of the footer looked a bit off: 
<img width="1440" alt="Screenshot 2024-12-23 at 12 17 32 AM" src="https://github.com/user-attachments/assets/ad908a3d-b464-4801-aab8-a7c7178fbd58" />

So, I decided to update its design:
<img width="1437" alt="Screenshot 2024-12-23 at 12 44 17 AM" src="https://github.com/user-attachments/assets/ca6ed1eb-7f13-4e75-8dba-6c331f1c923a" />

Please provide any other suggestions and any changes to the wording that could improve clarity and style.

**Comment by amri-tah** [comment]
Hey @akshayks13, you've been assigned this issue under Amrita Winter of Code! Please ensure to raise a PR by `28/12/2024`, or it will be reassigned to someone else. 
You could also add Privacy and Terms
Best of luck! 🫡

**Comment by rev-sin** [comment]
Queue me up as well, thanks in advance
